# Generated by Django 4.0.2 on 2022-04-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goals'),
        ),
        migrations.AlterField(
            model_name='saving',
            name='goals',
            field=models.ManyToManyField(blank=True, to='plans.Goal'),
        ),
    ]
