# Generated by Django 4.0.2 on 2022-04-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_goal_image_alter_saving_goals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='actual_price',
            new_name='price',
        ),
    ]
