# Generated by Django 4.0.2 on 2022-04-24 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0002_goal_created_at_goal_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='collected_amount',
            new_name='collected',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='is_fullField',
        ),
        migrations.AddField(
            model_name='goal',
            name='is_accomplished',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
