# Generated by Django 4.0.2 on 2022-04-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_rename_actual_price_goal_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ('-at',)},
        ),
        migrations.AlterModelOptions(
            name='saving',
            options={'ordering': ('-at',)},
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='created_at',
            new_name='at',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='duration',
        ),
        migrations.AddField(
            model_name='saving',
            name='at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
