# Generated by Django 4.0.2 on 2022-04-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_budget_options_alter_saving_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='is_accomplished',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
