# Generated by Django 4.0.2 on 2022-04-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_goal_is_accomplished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saving',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='user',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='Saving',
        ),
    ]
