# Generated by Django 4.0.2 on 2022-04-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_remove_saving_goals_remove_saving_user_delete_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('updated', 'updated'), ('deleted', 'deleted'), ('blank', 'blank')], default='blank', max_length=10),
        ),
    ]
