# Generated by Django 4.0.2 on 2022-04-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_notifications_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True)),
                ('_from', models.DateField(verbose_name='from')),
                ('to', models.DateField()),
                ('total_amount', models.FloatField()),
                ('amount_left', models.FloatField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('has_expired', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'ordering': ('-issued_at',),
            },
        ),
        migrations.AlterField(
            model_name='goal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
