# Generated by Django 4.0.2 on 2022-04-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_budget_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='amount_left',
            new_name='amount_used',
        ),
    ]
