# Generated by Django 4.0.2 on 2022-08-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_rename_amount_left_budget_amount_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount_used',
            field=models.FloatField(default=0.0),
        ),
    ]
