# Generated by Django 4.0.2 on 2022-09-15 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_alter_budget__from_alter_budget_amount_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='from'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goals'),
        ),
    ]
