# Generated by Django 4.0.2 on 2022-11-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0014_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='has_expired',
        ),
        migrations.AlterField(
            model_name='budget',
            name='to',
            field=models.DateTimeField(verbose_name='to'),
        ),
    ]
