# Generated by Django 4.0.2 on 2022-11-30 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0015_remove_budget_has_expired_alter_budget_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='is_accomplished',
        ),
    ]
