# Generated by Django 4.0.2 on 2022-12-06 12:00

from django.db import migrations, models
import expense_tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0016_remove_goal_is_accomplished'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ('-updated',)},
        ),
        migrations.AddField(
            model_name='budget',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount_used',
            field=models.FloatField(default=0.0, editable=False, validators=[expense_tracker.validators.number_lt_zero]),
        ),
    ]
