# Generated by Django 4.0.2 on 2022-12-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0017_alter_budget_options_budget_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ('-issued_at',)},
        ),
        migrations.AddField(
            model_name='notifications',
            name='signal',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('source', 'Source'), ('category', 'Category'), ('budget', 'Budget'), ('goal', 'Goal'), ('profile', 'Profile'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
