# Generated by Django 4.0.2 on 2022-12-29 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0018_alter_budget_options_notifications_signal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='amount_used',
        ),
    ]
