# Generated by Django 4.0.2 on 2022-04-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_category_desc_category_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='expense_receipt/'),
        ),
    ]
