# Generated by Django 4.0.2 on 2022-04-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_rename_amount_left_budget_amount_used'),
        ('api', '0006_expenses_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.budget'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
