# Generated by Django 4.0.2 on 2022-07-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_expenses_budget_alter_expenses_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.ManyToManyField(blank=True, to='api.Source'),
        ),
    ]
