# Generated by Django 4.0.2 on 2022-08-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_income_desc_alter_income_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='expenses'),
        ),
    ]
