# Generated by Django 4.0.2 on 2022-12-22 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0018_alter_budget_options_notifications_signal_and_more'),
        ('api', '0010_alter_expenses_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='budget',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='plans.budget'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenses',
            name='categories',
            field=models.ManyToManyField(blank=True, to='api.Category'),
        ),
    ]
