# Generated by Django 4.0.2 on 2022-12-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_expenses_budget_alter_expenses_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.FloatField(),
        ),
    ]
