# Generated by Django 4.0.2 on 2022-04-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photoURL',
            field=models.ImageField(height_field=300, null=True, upload_to='', width_field=300),
        ),
    ]
