# Generated by Django 4.0.2 on 2022-04-29 18:53

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_profile_firstname_alter_profile_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photoURL',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
