# Generated by Django 4.0.2 on 2022-08-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_profile_photourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photoURL',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
