# Generated by Django 4.0.2 on 2022-11-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_profile_email_alter_profile_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='firstName',
            field=models.CharField(blank=True, default=3, max_length=50),
            preserve_default=False,
        ),
    ]
